[package]
name = "wincode"
version = "0.1.0"
authors.workspace = true
description = "Fast bincode de/serialization with placement initialization"
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs", "-D", "warnings"]

[features]
default = ["std", "derive"]
alloc = []
std = ["alloc", "thiserror/std"]
solana-short-vec = ["dep:solana-short-vec"]
derive = ["dep:wincode-derive"]

[dependencies]
paste = "1.0.15"
solana-short-vec = { version = "3.0.0", optional = true }
thiserror = { version = "2.0.16", default-features = false }
wincode-derive = { path = "../wincode-derive", optional = true }

[dev-dependencies]
bincode = { version = "1.3.3" }
proptest = { version = "1.8.0" }
rand = { version = "0.8.5" }
serde = { version = "1.0.227", features = ["derive"] }
solana-short-vec = { version = "3.0.0" }
