[workspace]
members = ["wincode", "wincode-derive"]
resolver = "2"

[workspace.lints.clippy]
default_trait_access = "deny"
manual_let_else = "deny"
used_underscore_binding = "deny"

[workspace.lints.rust]
warnings = "deny"

[workspace.package]
version = "0.1.0"
authors = ["Anza Maintainers <maintainers@anza.xyz>"]
repository = "https://github.com/anza-xyz/wincode"
homepage = "https://anza.xyz/"
license = "Apache-2.0"
edition = "2021"
