name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  fmt:
    name: rustfmt & miri (nightly)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, miri
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: rustfmt (check)
        run: cargo +nightly fmt --all -- --check
      - name: miri (check)
        run: cargo +nightly miri test --all-features --all-targets --no-fail-fast

  lint-test:
    name: clippy & tests (stable)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: clippy (deny warnings)
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: tests
        run: cargo test --all-features --all-targets --no-fail-fast
