name: Dispatch continuous fuzzing

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    environment: fuzz
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          toolchain: nightly
          rustflags: ""

      - uses: dtolnay/install@d0dc46e85ffd2c174b5ac0489e17f95dae84fa5a # cargo-fuzz
      - run: cargo +nightly fuzz build --no-trace-compares

      - name: Prepare bundle
        run: ./fuzz/build-fuzz-bundle.sh

      - name: Upload corpus to FuzzCorp
        uses: asymmetric-research/fuzz-upload-action@0e367cafdc501772fd0fd7dc13bfa68d49222256 # v2.0.0
        with:
          upload_type: corpus
          upload_path: ./fuzz/corpus/roundtrip
          upload_args: --lineage roundtrip --kind seed
        env:
          FUZZ_ORGANIZATION: anza
          FUZZ_PROJECT: wincode
          FUZZ_API_KEY: ${{ secrets.FUZZ_API_KEY }}

      - name: Upload bundle to FuzzCorp
        uses: asymmetric-research/fuzz-upload-action@0e367cafdc501772fd0fd7dc13bfa68d49222256 # v2.0.0
        with:
          upload_type: bundle
          upload_path: ./fuzz/target/bundle
        env:
          FUZZ_ORGANIZATION: anza
          FUZZ_PROJECT: wincode
          FUZZ_API_KEY: ${{ secrets.FUZZ_API_KEY }}
